name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x gradlew

      - name: Build with Gradle Kotlin DSL (skip tests)
        run: ./gradlew build -x test

      - name: Confirm JAR exists
        run: ls -lh build/libs

      - name: Copy JAR and Dockerfile to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.AWS_SERVER }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          source: "build/libs/*.jar,Dockerfile"
          target: /home/ec2-user/app

      - name: SSH and deploy with Docker and create .env
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_SERVER }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ec2-user/app
            
            cat <<EOF > .env
            DB_URL=${{ secrets.DB_URL }}
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            EOF
            
            mv build/libs/*.jar app.jar || true
            docker stop springboot-app || true
            docker rm springboot-app || true
            docker build -t springboot-app .
            docker run -d -p 8080:8080 --name springboot-app --env-file .env springboot-app